import React, { createContext, useContext, useState } from 'react';

// Define the supported native languages
export type NativeLanguage = 'vi' | 'en';

export interface LanguageContextType {
  nativeLanguage: NativeLanguage | null;
  setNativeLanguage: (lang: NativeLanguage) => void;
  t: (key: keyof typeof translations['en']) => string;
}

export const translations = {
  vi: {
    // Nav / Sidebar
    dashboard: "Bảng điều khiển",
    translation: "Luyện dịch",
    listening: "Luyện nghe",
    grammar: "Ngữ pháp",
    vocabulary: "Từ vựng",
    games: "Trò chơi",
    premium: "Nâng cấp AI Pro",
    unlockPro: "Mở khoá AI Pro",
    logout: "Đăng xuất",

    // General Words
    continueLesson: "Tiếp tục bài học",
    activeObjective: "Mục tiêu hiện tại",
    xpProgress: "Tiến độ XP",
    dailyStreak: "Chuỗi ngày",
    days: "Ngày",
    willkommenBack: "Chào mừng trở lại",
    nextMilestone: "Mốc thử thách tiếp theo",
    completeToUnlock: "Hoàn thành để mở khoá",
    level: "Cấp độ",
    allModules: "Tất cả mô-đun",
    recommended: "Gợi ý cho bạn",
    mastered: "Đã thuần thục",

    // Home / Dashboard Setting Section
    settingsTitle: "Cài đặt ứng dụng",
    settingsSubtitle: "Tuỳ chỉnh trải nghiệm học tập và chọn ngôn ngữ mẹ đẻ của bạn.",
    chooseNativeLanguage: "Chọn ngôn ngữ mẹ đẻ",
    nativeLanguageLabel: "Ngôn ngữ mẹ đẻ",
    nativeLanguageDesc: "Toàn bộ hướng dẫn học, giải thích, feedback kiểm tra và phân tích ngữ pháp từ AI từ Delerny sẽ được hiển thị bằng ngôn ngữ này.",
    vietnamese: "🇻🇳 Tiếng Việt",
    english: "🇺🇸 English",
    saveSettings: "Cập nhật cài đặt",
    savedAlert: "Cài đặt đã được lưu thành công!",

    // Translation View
    translationPractice: "Luyện tập dịch thuật",
    translateToGerman: "Dịch sang tiếng Đức",
    yourTranslation: "Bản dịch của bạn",
    yourTranslationPlaceholder: "Nhập bản dịch tiếng Đức của bạn ở đây...",
    wordsCount: "từ",
    aiSupportTip: "Có AI hỗ trợ chấm sửa lỗi tự động",
    btnAnalyze: "Bắt đầu chấm bài viết",
    btnAnalyzing: "Đang chấm bài...",
    btnNextQuestion: "Chuyển sang câu tiếp theo",
    btnViewResults: "Xem kết quả chung cuộc",
    requestHint: "Yêu cầu gợi ý",
    revealAnswer: "Hiển thị đáp án",
    skipQuestion: "Đổi câu",
    aiEvaluation: "AI ĐÁNH GIÁ",
    waitingTranslation: "Chờ bản dịch của bạn...",
    waitingDesc: "Trí tuệ nhân tạo sẽ chấm lỗi ngữ pháp, độ tự nhiên và vốn từ của bạn ngay tức thì.",
    checkGrammar: "Kiểm tra Ngữ pháp",
    checkWordOrder: "Đánh giá vị trí từ",
    checkNaturalness: "Tính điểm tự nhiên",
    analyzingNuances: "Đang kiểm tra sắc thái...",
    analyzingDesc: "So sánh bản dịch với hàng triệu dữ liệu cấu trúc mẫu.",
    grammarGauge: "Ngữ pháp",
    naturalnessGauge: "Tự nhiên",
    vocabularyGauge: "Từ vựng",
    compareTranslations: "So sánh bản dịch",
    draftLabel: "Bản phác của bạn",
    correctLabel: "Đáp án đúng",
    improvementsTitle: "Chi tiết cải tiến",
    perfectDraft: "Không phát hiện sai sót nào! Bản dịch của bạn cực kỳ vững chãi.",
    closeMatchTip: "Bản dịch gần như chính xác tuyệt đối, chỉ cần điều chỉnh nhỏ về cách chọn lối văn.",
    nativeVariantTitle: "Biến thể bản xứ phong phú",
    naturalPhraingLabel: "Đúng quy chuẩn giao tiếp tự nhiên của người bản địa trong bối cảnh đời sống hàng ngày.",
    keyVocab: "Từ vựng mấu chốt",
    grammarDiagnosisHeader: "Chẩn đoán ngữ pháp",
    grammStatusOk: "Đạt chuẩn",
    grammStatusWarn: "Cần Chú Ý",
    articleAndGender: "Mạo từ & Giống học",
    hintTitle: "Gợi ý cách viết",

    // Translation Results
    practiceResults: "Kết quả luyện tập",
    earnedXpMsg: "Bạn đã tích luỹ được {score} XP trong bài tập này!",
    resultGreat: "Quá xuất sắc!",
    resultGood: "Nỗ lực tuyệt vời!",
    resultTryMore: "Hãy cố gắng thêm chút nữa!",
    feedbackGreat: "Kỹ năng dịch thuật của bạn cực kỳ vững vàng và tự nhiên như người bản xứ vậy!",
    feedbackGood: "Bạn đang tiến bộ rất nhanh! Việc luyện tập đều đặn sẽ giúp khắc phục lỗi trật tự từ vựng hiệu quả.",
    feedbackTryMore: "Luyện dịch chăm chỉ hơn để cải thiện độ trôi chảy nhé!",
    btnStartOver: "Bắt đầu lượt mới",

    // Onboarding Screen (Initial Selection)
    chooseNativeTitle: "Choose your native language",
    chooseNativeSubtitle: "This helps Delerny explain German lessons in the language you understand best.",
    continueBtn: "Continue",

    // Vocab & Dictation Specifics
    learnNewWords: "Học từ mới",
    mcQuiz: "Trắc nghiệm",
    articlesPractice: "Luyện der/die/das",
    flashcards: "Flashcard",
    fillBlank: "Điền từ",
    listeningTab: "Luyện nghe",
    noWordsFound: "Không tìm thấy từ vựng nào trong chủ đề này.",
    question: "Câu hỏi",
    correct: "Đúng",
    mẹo: "Mẹo",
    germNounsCapTip: "Mẹo: Tiếng Đức có phân biệt viết hoa danh từ (ví dụ: Eltern, Familie...)",
    progress: "Tiến độ",
    inputAnswer: "Nhập đáp án",
    inputGermanWordPlaceHolder: "Nhập từ tiếng Đức...",
    quickType: "Gõ nhanh:",
    excellentCorrect: "Tuyệt vời! Đáp án chính xác",
    incorrectTryAgain: "Cố lên! Đáp án chưa chính xác",
    correctAnswerIs: "Đáp án đúng:",
    exampleLabel: "Ví dụ:",
    continueBtnText: "Tiếp tục",
    checkBtnText: "Kiểm tra",
    selectCorrectMeaningPrompt: "CHỌN NGHĨA TIẾNG VIỆT ĐÚNG",
    clickSpeakerTip: "Mẹo: Click biểu tượng loa để nghe phát âm chính xác của từ vựng này.",
    selectBestMeaning: "Chọn nghĩa phù hợp nhất",
    nextQuestionBtn: "Tiếp theo",
    listenAndTypeGerman: "NGHE VÀ THUẬT LẠI TIẾNG ĐỨC",
    clickToPlayAudio: "Click để phát âm thanh của từ vựng",
    listeningPracticeReflexTip: "Luyện nghe phát âm giúp cải thiện phản xạ giao tiếp quốc tế.",
    typeGermanHeard: "Gõ từ khóa tiếng Đức nghe được...",
    veryGoodCorrectHeard: "Rất tốt! Bạn đã nghe chính xác",
    wrongHeardTryAgain: "Cố lên! Hãy xem kết quả",
    masteryPath: "Lộ trình học",
    vocabularyTitle: "Từ vựng tiếng Đức",
    vocabularyDesc: "Chọn trình độ học tập hiện tại. Mỗi cấp độ sẽ học các danh từ, động từ và cụm từ cốt lõi.",
    selectProficiency: "Chọn trình độ phù hợp",
    levelsAvailable: "4 cấp độ bài học",
    curriculumTitle: "Chương trình học",
    chaptersTitle: "Các chủ đề chính",
    allTopics: "Tất cả chủ đề",
    backToChapters: "Quay lại chủ đề học",
    grammarDrillsTitle: "Luyện ngữ pháp",
    derDieDasPracticeTitle: "Luyện tập Der / Die / Das",
    derDieDasPracticeDesc: "Phần luyện tập mạo từ tiếng Đức (Gợi ý dựa trên luật ngữ pháp).",
    einsteinAiIntro: "Học mọi từ vựng vững vàng với Einstein AI.",
    einsteinAiDetail: "Mở khoá nghiên cứu từ sâu sắc, ví dụ ngữ cảnh phong phú, và chế độ flashcard AI thông minh.",
    explorePremiumBtn: "Khám phá bản Pro",
    meaningLabel: "Nghĩa của từ",
    word: "Từ vựng",
    gender: "Giống",
    status: "Trạng thái",
    markStudy: "Đánh dấu học",

    // Dictation Trainer (Listening AI)
    aiListeningPractice: "Luyện nghe tiếng Đức AI",
    selectDictationTopic: "Chọn chủ đề chép chính tả",
    dictationBadge: "Nghe Chép (Dictation)",
    listeningDesc: "Phương pháp nghe chép cụ thể từng từ sẽ kích thích tư duy giống cách, mạo từ và mài giũa thính giác phản xạ cực kỳ tốc độ.",
    vocabVault: "100+ Câu luyện tập",
    diverseDistribution: "5 Chủ đề đa dạng",
    instantFeedback: "AI chấm điểm phản hồi tức thì",
    listeningResultsTitle: "Kết quả luyện nghe",
    listeningEarnedXpMsg: "Bạn đã tích luỹ được {amount} XP trong bài tập này!",
    resultsRatingGreat: "Quá xuất sắc!",
    resultsRatingGood: "Nỗ lực tuyệt vời!",
    resultsRatingTryMore: "Hãy cố gắng thêm chút nữa!",
    excelFeedback: "Độ nhạy âm thính giác tiếng Đức của bạn cực kỳ tuyệt vời! Viết đúng mạo từ và mỏ neo chính tả hoàn chỉnh.",
    goodFeedback: "Bạn đang nghe tốt lên rõ rệt! Chép chính tả thường xuyên sẽ bù đắp phản xạ câm và đuôi giống nhanh chóng.",
    tryMoreFeedback: "Hãy nghe lại nhiều lần hơn nữa để cải thiện khả năng phân biệt âm đuôi của từ nhé!",
    startNewRound: "Bắt đầu lượt mới",
    selectOtherTopic: "Chọn chủ đề khác",
    dictationChallenge: "Thử thách nghe chép chính tả",
    replaysLeftLabel: "Lượt nghe còn lại:",
    replayLabel: "Nghe lại",
    pausePlayback: "Tạm dừng phát",
    playGermanAudio: "Phát âm thanh câu tiếng Đức",
    inputDictationDraft: "Nhập bản chép chính tả",
    dictationPlaceholder: "Nghe audio và gõ lại tiếng Đức bạn nghe được...",
    typeEveryWordExactly: "Gõ từng từ chính xác",
    requestHintBtn: "Yêu cầu gợi ý",
    showAnswerBtn: "Hiển thị đáp án",
    skipBtn: "Bỏ qua",
    checkDictationBtn: "Kiểm tra kết quả chính tả",
    analysisResultsTitle: "KẾT QUẢ PHÂN TÍCH",
    aiPowered: "AI Powered",
    noResultsYet: "Chưa có kết quả",
    listeningInstructions: "Nghe kỹ audio tiếng Đức phía bên trái rồi gõ lại những gì tai nghe được vào ô nhập liệu nhé.",
    preciseWordMatching: "So khớp tỉ mỉ từng từ",
    percentageAnalysis: "Hệ thống phân tích chính xác %",
    umlautCorrection: "Sửa lỗi umlaut ö, ä, ü, ß",
    accuracy: "Chính xác",
    replaysLeft: "Lượt thừa",
    skills: "Kỹ năng",
    sentenceMatching: "So khớp câu viết",
    standardGermanAnswer: "Đáp án tiếng Đức chuẩn",
    misspelledUnmatchedWords: "Những từ viết sai / chưa khớp",
    magnificent: "Tuyệt mỹ!",
    perfectListeningFeedback: "Bản nghe chép của bạn không mắc phải bất kỳ lỗi chính tả hay bỏ sót từ nào. Giác quan tiếng Đức của bạn rất nhạy Bén!",
    practiceAchieve: "Thành quả luyện tập",
    correctTranslationNote: "Dịch nghĩa từ chuẩn:",
    greetingsTopicTitle: "Chào hỏi & Cơ bản",
    greetingsTopicViTitle: "Chào hỏi & Đàm thoại cơ bản",
    greetingsTopicDesc: "Giới thiệu bản thân, các câu chào hỏi lịch sự hàng ngày và đàm thoại xã giao cơ bản.",
    travelTopicTitle: "Du lịch & Chỉ đường",
    travelTopicViTitle: "Hỏi đường & Du lịch",
    travelTopicDesc: "Hỏi đường, cách bắt tàu xe, giao tiếp cơ bản tại ga sân bay hoặc khi đi nghỉ dưỡng.",
    dailyTopicTitle: "Đời sống hàng ngày",
    dailyTopicViTitle: "Sinh hoạt & Đời sống hàng ngày",
    dailyTopicDesc: "Gọi món ăn tại nhà hàng, hỏi giờ giấc, mua sắm và trao đổi về thời tiết hàng ngày.",
    workTopicTitle: "Công sở & Công việc",
    workTopicViTitle: "Giao tiếp công sở & Công việc và sự nghiệp",
    workTopicDesc: "Trao đổi với đồng nghiệp, viết email công việc, thuật lại các hoạt động thời gian biểu công sở.",
    numbersTopicTitle: "Các con số (0-100)",
    numbersTopicViTitle: "Chữ số và Khoản đếm thường nhật",
    numbersTopicDesc: "Phản xạ nghe chép chữ số, số đếm từ 0 đến 100 chính xác để mua sắm, thanh toán hóa đơn.",
    exitBtn: "Thoát",
  },
  en: {
    // Nav / Sidebar
    dashboard: "Dashboard",
    translation: "Translation",
    listening: "Listening",
    grammar: "Grammar",
    vocabulary: "Vocabulary",
    games: "Games",
    premium: "Unlock AI Pro",
    unlockPro: "Unlock AI Pro",
    logout: "Logout",

    // General Words
    continueLesson: "Continue Lesson",
    activeObjective: "Active Objective",
    xpProgress: "XP Progress",
    dailyStreak: "Daily Streak",
    days: "Days",
    willkommenBack: "Welcome back",
    nextMilestone: "Next Milestone",
    completeToUnlock: "Complete to unlock",
    level: "Level",
    allModules: "All Modules",
    recommended: "Recommended",
    mastered: "Mastered",

    // Home / Dashboard Setting Section
    settingsTitle: "Application Settings",
    settingsSubtitle: "Customize your learning experience and your native language setting.",
    chooseNativeLanguage: "Select Native Language",
    nativeLanguageLabel: "Native Language",
    nativeLanguageDesc: "All AI instructions, translations, notes, vocabulary feedback, and grammar analyses from Delerny will be explained in this language.",
    vietnamese: "🇻🇳 Tiếng Việt (Vietnamese)",
    english: "🇺🇸 English",
    saveSettings: "Update Settings",
    savedAlert: "Settings saved successfully!",

    // Translation View
    translationPractice: "Translation Practice",
    translateToGerman: "Translate to German",
    yourTranslation: "Your answer",
    yourTranslationPlaceholder: "Enter your German translation here...",
    wordsCount: "words",
    aiSupportTip: "AI automated feedback enabled",
    btnAnalyze: "Analyze Translation",
    btnAnalyzing: "Analyzing...",
    btnNextQuestion: "Next sentence",
    btnViewResults: "View overall ranking",
    requestHint: "Request hint",
    revealAnswer: "Reveal answer",
    skipQuestion: "Change sentence",
    aiEvaluation: "AI EVALUATION",
    waitingTranslation: "Awaiting your translation...",
    waitingDesc: "Our artificial intelligence will grade your grammar, naturalness, and vocabulary immediately.",
    checkGrammar: "Check Grammar",
    checkWordOrder: "Evaluate word order",
    checkNaturalness: "Determine naturalness",
    analyzingNuances: "Analyzing nuances...",
    analyzingDesc: "Comparing your translation with millions of standard structural patterns.",
    grammarGauge: "Grammar",
    naturalnessGauge: "Naturalness",
    vocabularyGauge: "Vocabulary",
    compareTranslations: "Compare translation",
    draftLabel: "Your draft",
    correctLabel: "Correct answer",
    improvementsTitle: "Improvement details",
    perfectDraft: "No mistakes detected! Your translation is highly accurate.",
    closeMatchTip: "Your translation is almost perfectly correct, just needs minor adjustments in phrasing style.",
    nativeVariantTitle: "Rich native variants",
    naturalPhraingLabel: "Aligned with natural communication standards of native speakers in daily life contexts.",
    keyVocab: "Key Vocabulary",
    grammarDiagnosisHeader: "Grammar Diagnosis",
    grammStatusOk: "Correct",
    grammStatusWarn: "Pay attention",
    articleAndGender: "Articles & Genders",
    hintTitle: "Hint",

    // Translation Results
    practiceResults: "Practice Results",
    earnedXpMsg: "You have accumulated {score} XP in this exercise!",
    resultGreat: "Absolutely superb!",
    resultGood: "Excellent effort!",
    resultTryMore: "Try a little harder next time!",
    feedbackGreat: "Your translation skills are incredibly robust and natural like a native!",
    feedbackGood: "You are making fast progress! Regular practice will reduce word order errors effectively.",
    feedbackTryMore: "Keep practicing translations to improve your fluency!",
    btnStartOver: "Start New Round",

    // Onboarding Screen (Initial Selection)
    chooseNativeTitle: "Choose your native language",
    chooseNativeSubtitle: "This helps Delerny explain German lessons in the language you understand best.",
    continueBtn: "Continue",

    // Vocab & Dictation Specifics
    learnNewWords: "Learn new words",
    mcQuiz: "Quiz",
    articlesPractice: "Articles Drill",
    flashcards: "Flashcards",
    fillBlank: "Fill Blank",
    listeningTab: "Listen",
    noWordsFound: "No vocabulary words found in this theme.",
    question: "Question",
    correct: "Correct",
    mẹo: "Hint",
    germNounsCapTip: "Hint: German nouns are always capitalized (e.g., Eltern, Familie...)",
    progress: "Progress",
    inputAnswer: "Enter answer",
    inputGermanWordPlaceHolder: "Enter German word...",
    quickType: "Quick type:",
    excellentCorrect: "Excellent! Correct answer",
    incorrectTryAgain: "Keep going! Incorrect answer",
    correctAnswerIs: "Correct answer is:",
    exampleLabel: "Example:",
    continueBtnText: "Continue",
    checkBtnText: "Check",
    selectCorrectMeaningPrompt: "CHOOSE THE CORRECT MEANING",
    clickSpeakerTip: "Tip: Click the speaker icon to hear the correct pronunciation of this vocabulary word.",
    selectBestMeaning: "Select the best meaning",
    nextQuestionBtn: "Next",
    listenAndTypeGerman: "LISTEN AND TRANSCRIBE GERMAN",
    clickToPlayAudio: "Click to play pronunciation audio",
    listeningPracticeReflexTip: "Listening practice helps improve international communication reflexes.",
    typeGermanHeard: "Type the German words you heard...",
    veryGoodCorrectHeard: "Very good! You heard it correctly",
    wrongHeardTryAgain: "Keep trying! Let's view the results",
    masteryPath: "Mastery Path",
    vocabularyTitle: "German Vocabulary Library",
    vocabularyDesc: "Choose your current proficiency level. Each level introduces core nouns, verbs, and phrases essential for fluency.",
    selectProficiency: "Select Your Level",
    levelsAvailable: "4 Levels Available",
    curriculumTitle: "Curriculum",
    chaptersTitle: "Core Themes",
    allTopics: "All Themes",
    backToChapters: "Back to Chapters",
    grammarDrillsTitle: "Grammar Drills",
    derDieDasPracticeTitle: "Der Die Das Practice",
    derDieDasPracticeDesc: "German article practice drill (Hints based on grammatical gender rules).",
    einsteinAiIntro: "Master every word with Einstein AI.",
    einsteinAiDetail: "Unlock deep vocabulary analysis, contextual usage examples, and infinite AI-generated practice cards.",
    explorePremiumBtn: "Explore Premium Pro",
    meaningLabel: "Meaning",
    word: "Vocabulary word",
    gender: "Gender / Article",
    status: "Status",
    markStudy: "Study mark",

    // Dictation Trainer (Listening AI)
    aiListeningPractice: "AI German Listening Practice",
    selectDictationTopic: "Select a Dictation Topic",
    dictationBadge: "Dictation Drill",
    listeningDesc: "Methodical word-for-word writing sharpens your auditory reflexes, grammatical structure, and noun genders.",
    vocabVault: "100+ Sentences",
    diverseDistribution: "5 Diverse Categories",
    instantFeedback: "AI-powered real-time grading",
    listeningResultsTitle: "Listening Practice Finished",
    listeningEarnedXpMsg: "You have accumulated {amount} XP in this exercise!",
    resultsRatingGreat: "Absolutely superb!",
    resultsRatingGood: "Excellent effort!",
    resultsRatingTryMore: "Try a little harder next time!",
    excelFeedback: "Your German auditory precision is absolutely remarkable! Correct spelling of articles and words.",
    goodFeedback: "You are listening noticeably better! Regular dictation practice accelerates conversational absorption.",
    tryMoreFeedback: "Listen to the audios a few more times to better distinguish German word endings!",
    startNewRound: "Start New Round",
    selectOtherTopic: "Select Another Topic",
    dictationChallenge: "Dictation Challenge",
    replaysLeftLabel: "Replays remaining:",
    replayLabel: "Replay",
    pausePlayback: "Pause",
    playGermanAudio: "Play German Audio",
    inputDictationDraft: "Your dictation transcript",
    dictationPlaceholder: "Listen to the audio and transcribe what you hear in German...",
    typeEveryWordExactly: "Type every word accurately",
    requestHintBtn: "Request Hint",
    showAnswerBtn: "Show Answer",
    skipBtn: "Skip",
    checkDictationBtn: "Verify Dictation Accuracy",
    analysisResultsTitle: "ANALYSIS RESULTS",
    aiPowered: "AI Powered",
    noResultsYet: "No analyses yet",
    listeningInstructions: "Listen carefully to the German audio on the left and type what you hear into the input box.",
    preciseWordMatching: "Meticulous word-for-word matching",
    percentageAnalysis: "Precision percentage analysis",
    umlautCorrection: "Umlaut corrections for ö, ä, ü, ß",
    accuracy: "Accuracy",
    replaysLeft: "Replays remaining",
    skills: "Auditory skill",
    sentenceMatching: "Sentence matching comparison",
    standardGermanAnswer: "Standard German Answer",
    misspelledUnmatchedWords: "Misspellings / Unmatched words",
    magnificent: "Magnificent!",
    perfectListeningFeedback: "Your dictation transcript contains zero spelling or matching errors. Your German listening intuition is outstanding!",
    practiceAchieve: "Practice Achievements",
    correctTranslationNote: "English translation:",
    greetingsTopicTitle: "Greetings & Basics",
    greetingsTopicViTitle: "Greetings & Basic Conversation",
    greetingsTopicDesc: "Introduce yourself, daily polite phrases, and basic social talking triggers.",
    travelTopicTitle: "Travel & Directions",
    travelTopicViTitle: "Directions & Travel Topics",
    travelTopicDesc: "Asking for directions, catching local transits, and ordering at hubs.",
    dailyTopicTitle: "Daily Life Activities",
    dailyTopicViTitle: "Daily Life Customs",
    dailyTopicDesc: "Ordering at restaurants, asking for the time, shopping, and everyday weather.",
    workTopicTitle: "Office & Operations",
    workTopicViTitle: "Office Communication & Career",
    workTopicDesc: "Workmates dialogues, writing business letters, or recapping schedules.",
    numbersTopicTitle: "Numbers & Counting (0-100)",
    numbersTopicViTitle: "Listen & Dictate Numbers",
    numbersTopicDesc: "Improve your listening reflex for prices, years, phone numbers from 0 to 100.",
    exitBtn: "Exit",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [nativeLanguage, setNativeLanguageState] = useState<NativeLanguage | null>(() => {
    const saved = localStorage.getItem('nativeLanguage');
    if (saved === 'vi' || saved === 'en') {
      return saved;
    }
    return null;
  });

  const setNativeLanguage = (lang: NativeLanguage) => {
    setNativeLanguageState(lang);
    localStorage.setItem('nativeLanguage', lang);
  };

  const t = (key: keyof typeof translations['en']): string => {
    const lang = nativeLanguage || 'en'; // default fallback is english
    const dict = translations[lang] || translations['en'];
    return dict[key] || translations['en'][key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ nativeLanguage, setNativeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
